/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.*;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author VRB
 */
public class LogWindow extends javax.swing.JFrame 
{
    /**
     * Creates new form Principal_Window
     */
    public LogWindow(int rol) {
        initComponents();
        this.rol=rol;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        logInPanel = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        Label_Username = new javax.swing.JLabel();
        TextField_Username = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        Label_Password = new javax.swing.JLabel();
        Button_Register = new javax.swing.JButton();
        Button_Login = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        signInLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("teloTengo Sign In");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setName("LogWindow"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        logInPanel.setBackground(new java.awt.Color(255, 255, 255));
        logInPanel.setMinimumSize(new java.awt.Dimension(1366, 768));
        logInPanel.setName("logInPanel"); // NOI18N
        logInPanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        logInPanel.setLayout(null);

        registerLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        registerLabel.setText("If you don't have an acount");
        logInPanel.add(registerLabel);
        registerLabel.setBounds(550, 470, 210, 20);

        Label_Username.setBackground(new java.awt.Color(255, 255, 255));
        Label_Username.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Label_Username.setText("Username:");
        logInPanel.add(Label_Username);
        Label_Username.setBounds(550, 310, 70, 20);

        TextField_Username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logInPanel.add(TextField_Username);
        TextField_Username.setBounds(630, 310, 230, 20);

        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logInPanel.add(PasswordField);
        PasswordField.setBounds(630, 350, 230, 20);

        Label_Password.setBackground(new java.awt.Color(255, 255, 255));
        Label_Password.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Label_Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Password.setText("Password:");
        logInPanel.add(Label_Password);
        Label_Password.setBounds(550, 350, 70, 20);

        Button_Register.setBackground(new java.awt.Color(255, 255, 255));
        Button_Register.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Button_Register.setForeground(new java.awt.Color(255, 153, 0));
        Button_Register.setText("Register here");
        Button_Register.setAutoscrolls(true);
        Button_Register.setBorderPainted(false);
        Button_Register.setContentAreaFilled(false);
        Button_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Register.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Button_Register.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Button_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RegisterActionPerformed(evt);
            }
        });
        logInPanel.add(Button_Register);
        Button_Register.setBounds(740, 470, 123, 20);

        Button_Login.setBackground(new java.awt.Color(255, 255, 255));
        Button_Login.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Button_Login.setForeground(new java.awt.Color(255, 153, 0));
        Button_Login.setText("Login");
        Button_Login.setBorderPainted(false);
        Button_Login.setContentAreaFilled(false);
        Button_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Login.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Button_Login.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Button_Login.setMargin(new java.awt.Insets(2, 14, 2, 0));
        Button_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LoginActionPerformed(evt);
            }
        });
        logInPanel.add(Button_Login);
        Button_Login.setBounds(800, 380, 60, 20);

        jSeparator1.setForeground(new java.awt.Color(153, 204, 255));
        logInPanel.add(jSeparator1);
        jSeparator1.setBounds(500, 460, 390, 10);

        signInLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(255, 153, 0));
        signInLabel.setText("Sign In");
        logInPanel.add(signInLabel);
        signInLabel.setBounds(480, 230, 100, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/teloTengo.png"))); // NOI18N
        logInPanel.add(logo);
        logo.setBounds(60, 30, 400, 130);

        getContentPane().add(logInPanel);
        logInPanel.setBounds(0, 0, 1366, 768);

        getAccessibleContext().setAccessibleName("teloTengo");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LoginActionPerformed
        // TODO add your handling code here:
        char [] password_original = PasswordField.getPassword();
        String password = new String(password_original);
        boolean answer=User_Controller.IsUser(TextField_Username.getText(), password); 

        if (answer)
        {
           // int rol;
            //rol=User_Controller.getUser(TextField_Username.getText()).getRol();
            
            if (rol==1)//Si es administrador, abrir módulo administrador
            {          
                        adminWindow = new AdminModWindow(TextField_Username.getText());
                        signedIn = true;
                        adminWindow.setVisible(true);
                        this.dispose();                
            }
            if (rol==2){
                
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Intente de nuevo","Usuario o Contraseña Incorrecta",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Button_LoginActionPerformed

    private void Button_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RegisterActionPerformed
        // TODO add your handling code here:
        Register_Window register = new Register_Window(rol);
        register.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Button_RegisterActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogWindow(rol).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Login;
    private javax.swing.JButton Button_Register;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_Username;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField TextField_Username;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel signInLabel;
    // End of variables declaration//GEN-END:variables
   AdminModWindow adminWindow = new AdminModWindow();
   Principal principalWindow; 
   InventoryWindow invWindow = new InventoryWindow(); 
   private static boolean signedIn; //valida si el usuario está logeado en el sistema
   private static int rol; //rol del usuario que se está logeando
}
