/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.*;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author VRB
 */
public class LogWindow extends javax.swing.JFrame 
{
    /**
     * Creates new form Principal_Window
     */
    public LogWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logInPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Label_Username = new javax.swing.JLabel();
        TextField_Username = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        Label_Password = new javax.swing.JLabel();
        Button_Register = new javax.swing.JButton();
        Button_Login = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Menu_Bar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("teloTengo Sign In");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(661, 594));
        setName("LogWindow"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        logInPanel.setBackground(new java.awt.Color(255, 255, 255));
        logInPanel.setMinimumSize(new java.awt.Dimension(661, 594));
        logInPanel.setName("logInPanel"); // NOI18N
        logInPanel.setPreferredSize(new java.awt.Dimension(661, 594));
        logInPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel1.setText("If you don't have an acount");
        logInPanel.add(jLabel1);
        jLabel1.setBounds(100, 320, 210, 20);

        Label_Username.setBackground(new java.awt.Color(255, 255, 255));
        Label_Username.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Label_Username.setText("Username:");
        logInPanel.add(Label_Username);
        Label_Username.setBounds(100, 140, 70, 32);

        TextField_Username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logInPanel.add(TextField_Username);
        TextField_Username.setBounds(100, 170, 230, 20);

        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logInPanel.add(PasswordField);
        PasswordField.setBounds(100, 230, 230, 20);

        Label_Password.setBackground(new java.awt.Color(255, 255, 255));
        Label_Password.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Label_Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Password.setText("Password:");
        logInPanel.add(Label_Password);
        Label_Password.setBounds(100, 200, 70, 32);

        Button_Register.setBackground(new java.awt.Color(255, 255, 255));
        Button_Register.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Button_Register.setForeground(new java.awt.Color(255, 153, 0));
        Button_Register.setText("Register here");
        Button_Register.setAutoscrolls(true);
        Button_Register.setBorderPainted(false);
        Button_Register.setContentAreaFilled(false);
        Button_Register.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Button_Register.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Button_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RegisterActionPerformed(evt);
            }
        });
        logInPanel.add(Button_Register);
        Button_Register.setBounds(290, 320, 123, 20);

        Button_Login.setBackground(new java.awt.Color(255, 255, 255));
        Button_Login.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Button_Login.setForeground(new java.awt.Color(255, 153, 0));
        Button_Login.setText("Login");
        Button_Login.setBorderPainted(false);
        Button_Login.setContentAreaFilled(false);
        Button_Login.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Button_Login.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Button_Login.setMargin(new java.awt.Insets(2, 14, 2, 0));
        Button_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LoginActionPerformed(evt);
            }
        });
        logInPanel.add(Button_Login);
        Button_Login.setBounds(270, 260, 60, 20);

        jSeparator1.setForeground(new java.awt.Color(153, 204, 255));
        logInPanel.add(jSeparator1);
        jSeparator1.setBounds(70, 310, 390, 10);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Sign In");
        logInPanel.add(jLabel2);
        jLabel2.setBounds(100, 100, 100, 30);

        getContentPane().add(logInPanel);
        logInPanel.setBounds(0, 0, 660, 590);
        setJMenuBar(Menu_Bar);

        getAccessibleContext().setAccessibleName("teloTengo");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LoginActionPerformed
        // TODO add your handling code here:
        char [] password_original = PasswordField.getPassword();
        String password = new String(password_original);
        boolean answer=User_Controller.IsUser(TextField_Username.getText(), password); 

        if (answer)
        {
            int rol;
            rol=User_Controller.getUser(TextField_Username.getText()).getRol();
            
            if (rol==1)
            {          
                        adminWindow = new AdminModWindow(TextField_Username.getText());            
                        adminWindow.setVisible(true);
                        this.dispose();                
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Intente de nuevo","Usuario o Contraseña Incorrecta",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Button_LoginActionPerformed

    private void Button_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RegisterActionPerformed
        // TODO add your handling code here:
        Register_Window register = new Register_Window();
        register.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Button_RegisterActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogWindow().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Login;
    private javax.swing.JButton Button_Register;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_Username;
    private javax.swing.JMenuBar Menu_Bar;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField TextField_Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel logInPanel;
    // End of variables declaration//GEN-END:variables
   AdminModWindow adminWindow = new AdminModWindow();

}
