/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

/**
 *
 * @author LaMitologica
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal(boolean signedIn, String userName) {
        initComponents();
        this.userName_Label.setVisible(false);
        this.signedIn=signedIn;
        this.userName = userName;
        
        if (signedIn)
        {
            this.userName_Label.setText(userName);
            this.userName_Label.setVisible(signedIn);            
            
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        principalPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        adminMod_Button = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        miCuenta_Button = new javax.swing.JButton();
        userName_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("teloTengo Home");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1366, 768));
        setName("principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1366, 768));

        principalPanel.setBackground(new java.awt.Color(255, 255, 255));
        principalPanel.setAutoscrolls(true);
        principalPanel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        principalPanel.setMinimumSize(new java.awt.Dimension(0, 768));
        principalPanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        principalPanel.setLayout(new java.awt.GridBagLayout());

        searchTextField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 644;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(140, 330, 0, 0);
        principalPanel.add(searchTextField, gridBagConstraints);

        searchButton.setBackground(new java.awt.Color(51, 51, 51));
        searchButton.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(51, 51, 51));
        searchButton.setText("GO");
        searchButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(140, 0, 0, 0);
        principalPanel.add(searchButton, gridBagConstraints);

        adminMod_Button.setBackground(new java.awt.Color(255, 255, 255));
        adminMod_Button.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        adminMod_Button.setForeground(new java.awt.Color(255, 204, 51));
        adminMod_Button.setText("Entrar al múdulo de Administración");
        adminMod_Button.setBorderPainted(false);
        adminMod_Button.setContentAreaFilled(false);
        adminMod_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminMod_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMod_ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(370, 60, 35, 0);
        principalPanel.add(adminMod_Button, gridBagConstraints);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/teloTengo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = -20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 0);
        principalPanel.add(logo, gridBagConstraints);

        miCuenta_Button.setBackground(new java.awt.Color(255, 255, 255));
        miCuenta_Button.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        miCuenta_Button.setForeground(new java.awt.Color(255, 204, 51));
        miCuenta_Button.setText("Mi Cuenta");
        miCuenta_Button.setBorderPainted(false);
        miCuenta_Button.setContentAreaFilled(false);
        miCuenta_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miCuenta_Button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        miCuenta_Button.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        miCuenta_Button.setMargin(new java.awt.Insets(2, 0, 2, 0));
        miCuenta_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCuenta_ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 46);
        principalPanel.add(miCuenta_Button, gridBagConstraints);

        userName_Label.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        userName_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userName_Label.setText("texto");
        userName_Label.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 171;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        principalPanel.add(userName_Label, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void miCuenta_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCuenta_ButtonActionPerformed
        // TODO add your handling code here:
      LogWindow logWindow = new LogWindow(1);
      logWindow.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_miCuenta_ButtonActionPerformed

    private void adminMod_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMod_ButtonActionPerformed
        // TODO add your handling code here:
        LogWindow logWindow = new LogWindow(2);
        logWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminMod_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(signedIn,userName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminMod_Button;
    private javax.swing.JLabel logo;
    private javax.swing.JButton miCuenta_Button;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel userName_Label;
    // End of variables declaration//GEN-END:variables
    private static boolean signedIn;
    private static String userName;

}
