/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

/**
 *
 * @author LaMitologica
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal(boolean signedIn) {
        initComponents();
        this.signedIn=signedIn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        adminMod_Button = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        miCuenta_Button = new javax.swing.JButton();
        userName_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principalPanel.setBackground(new java.awt.Color(255, 255, 255));
        principalPanel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        principalPanel.setMinimumSize(new java.awt.Dimension(661, 594));
        principalPanel.setLayout(null);

        searchTextField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });
        principalPanel.add(searchTextField);
        searchTextField.setBounds(40, 170, 460, 40);

        searchButton.setBackground(new java.awt.Color(51, 51, 51));
        searchButton.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(51, 51, 51));
        searchButton.setText("GO");
        searchButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        principalPanel.add(searchButton);
        searchButton.setBounds(500, 170, 40, 40);

        adminMod_Button.setBackground(new java.awt.Color(255, 255, 255));
        adminMod_Button.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        adminMod_Button.setForeground(new java.awt.Color(255, 204, 51));
        adminMod_Button.setText("Entrar al múdulo de Administración");
        adminMod_Button.setBorderPainted(false);
        adminMod_Button.setContentAreaFilled(false);
        adminMod_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMod_ButtonActionPerformed(evt);
            }
        });
        principalPanel.add(adminMod_Button);
        adminMod_Button.setBounds(220, 570, 260, 23);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/teloTengo.png"))); // NOI18N
        principalPanel.add(logo);
        logo.setBounds(40, 20, 400, 130);

        miCuenta_Button.setBackground(new java.awt.Color(255, 255, 255));
        miCuenta_Button.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        miCuenta_Button.setForeground(new java.awt.Color(255, 204, 51));
        miCuenta_Button.setText("Mi Cuenta");
        miCuenta_Button.setBorderPainted(false);
        miCuenta_Button.setContentAreaFilled(false);
        miCuenta_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCuenta_ButtonActionPerformed(evt);
            }
        });
        principalPanel.add(miCuenta_Button);
        miCuenta_Button.setBounds(560, 0, 100, 30);

        userName_Label.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        userName_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userName_Label.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        principalPanel.add(userName_Label);
        userName_Label.setBounds(370, 0, 200, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void miCuenta_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCuenta_ButtonActionPerformed
        // TODO add your handling code here:
      LogWindow logWindow = new LogWindow(2);
      logWindow.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_miCuenta_ButtonActionPerformed

    private void adminMod_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMod_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminMod_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(signedIn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminMod_Button;
    private javax.swing.JLabel logo;
    private javax.swing.JButton miCuenta_Button;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel userName_Label;
    // End of variables declaration//GEN-END:variables
    private static boolean signedIn;

}
